### ISSUE TITLE
LLAMA exited unexpectedly using  llama-3-chinese-8b-instruct-v3-gguf model

### ISSUE THREAD

**Issue by kellenwang1017** [gudatr/godot-ai-rpg#5]
```
Godot Engine v4.2.2.stable.mono.official.15073afe3 - https://godotengine.org
Vulkan API 1.2.231 - Forward+ - Using Vulkan Device #0: Apple - Apple M2 Max
 
[LLAMA][00:00:00:743] Detected MacOS on Arm64
[LLAMA][00:00:00:803] llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from ./../../llama/model/model.gguf (version GGUF V3 (latest))
[LLAMA][00:00:00:804] llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
[LLAMA][00:00:00:804] llama_model_loader: - kv   0:                       general.architecture str              = llama
[LLAMA][00:00:00:804] llama_model_loader: - kv   1:                               general.name str              = llama-3-chinese-8b-instruct-v3
[LLAMA][00:00:00:804] llama_model_loader: - kv   2:                          llama.block_count u32              = 32
[LLAMA][00:00:00:804] llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
[LLAMA][00:00:00:804] llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
[LLAMA][00:00:00:804] llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
[LLAMA][00:00:00:804] llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
[LLAMA][00:00:00:804] llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
[LLAMA][00:00:00:804] llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
[LLAMA][00:00:00:804] llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
[LLAMA][00:00:00:804] llama_model_loader: - kv  10:                          general.file_type u32              = 7
[LLAMA][00:00:00:804] llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
[LLAMA][00:00:00:804] llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
[LLAMA][00:00:00:804] llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
[LLAMA][00:00:00:804] llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
[LLAMA][00:00:00:818] llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
[LLAMA][00:00:00:822] llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
[LLAMA][00:00:00:854] llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
[LLAMA][00:00:00:854] llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
[LLAMA][00:00:00:854] llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128009
[LLAMA][00:00:00:854] llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
[LLAMA][00:00:00:854] llama_model_loader: - kv  21:               general.quantization_version u32              = 2
[LLAMA][00:00:00:854] llama_model_loader: - type  f32:   65 tensors
[LLAMA][00:00:00:854] llama_model_loader: - type q8_0:  226 tensors
[LLAMA][00:00:01:122] llm_load_vocab: special tokens definition check successful ( 256/128256 ).
[LLAMA][00:00:01:123] llm_load_print_meta: format           = GGUF V3 (latest)
[LLAMA][00:00:01:123] llm_load_print_meta: arch             = llama
[LLAMA][00:00:01:123] llm_load_print_meta: vocab type       = BPE
[LLAMA][00:00:01:123] llm_load_print_meta: n_vocab          = 128256
[LLAMA][00:00:01:123] llm_load_print_meta: n_merges         = 280147
[LLAMA][00:00:01:123] llm_load_print_meta: n_ctx_train      = 8192
[LLAMA][00:00:01:123] llm_load_print_meta: n_embd           = 4096
[LLAMA][00:00:01:123] llm_load_print_meta: n_head           = 32
[LLAMA][00:00:01:123] llm_load_print_meta: n_head_kv        = 8
[LLAMA][00:00:01:123] llm_load_print_meta: n_layer          = 32
[LLAMA][00:00:01:123] llm_load_print_meta: n_rot            = 128
[LLAMA][00:00:01:123] llm_load_print_meta: n_embd_head_k    = 128
[LLAMA][00:00:01:123] llm_load_print_meta: n_embd_head_v    = 128
[LLAMA][00:00:01:123] llm_load_print_meta: n_gqa            = 4
[LLAMA][00:00:01:123] llm_load_print_meta: n_embd_k_gqa     = 1024
[LLAMA][00:00:01:123] llm_load_print_meta: n_embd_v_gqa     = 1024
[LLAMA][00:00:01:123] llm_load_print_meta: f_norm_eps       = 0.0e+00
[LLAMA][00:00:01:123] llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
[LLAMA][00:00:01:123] llm_load_print_meta: f_clamp_kqv      = 0.0e+00
[LLAMA][00:00:01:123] llm_load_print_meta: f_max_alibi_bias = 0.0e+00
[LLAMA][00:00:01:123] llm_load_print_meta: f_logit_scale    = 0.0e+00
[LLAMA][00:00:01:123] llm_load_print_meta: n_ff             = 14336
[LLAMA][00:00:01:123] llm_load_print_meta: n_expert         = 0
[LLAMA][00:00:01:123] llm_load_print_meta: n_expert_used    = 0
[LLAMA][00:00:01:123] llm_load_print_meta: causal attn      = 1
[LLAMA][00:00:01:123] llm_load_print_meta: pooling type     = 0
[LLAMA][00:00:01:123] llm_load_print_meta: rope type        = 0
[LLAMA][00:00:01:123] llm_load_print_meta: rope scaling     = linear
[LLAMA][00:00:01:123] llm_load_print_meta: freq_base_train  = 500000.0
[LLAMA][00:00:01:123] llm_load_print_meta: freq_scale_train = 1
[LLAMA][00:00:01:123] llm_load_print_meta: n_yarn_orig_ctx  = 8192
[LLAMA][00:00:01:123] llm_load_print_meta: rope_finetuned   = unknown
[LLAMA][00:00:01:123] llm_load_print_meta: ssm_d_conv       = 0
[LLAMA][00:00:01:123] llm_load_print_meta: ssm_d_inner      = 0
[LLAMA][00:00:01:123] llm_load_print_meta: ssm_d_state      = 0
[LLAMA][00:00:01:123] llm_load_print_meta: ssm_dt_rank      = 0
[LLAMA][00:00:01:123] llm_load_print_meta: model type       = 8B
[LLAMA][00:00:01:123] llm_load_print_meta: model ftype      = Q8_0
[LLAMA][00:00:01:123] llm_load_print_meta: model params     = 8.03 B
[LLAMA][00:00:01:123] llm_load_print_meta: model size       = 7.95 GiB (8.50 BPW) 
[LLAMA][00:00:01:123] llm_load_print_meta: general.name     = llama-3-chinese-8b-instruct-v3
[LLAMA][00:00:01:123] llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
[LLAMA][00:00:01:123] llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
[LLAMA][00:00:01:123] llm_load_print_meta: LF token         = 128 'Ä'
[LLAMA][00:00:01:123] llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
[LLAMA][00:00:01:123] llm_load_tensors: ggml ctx size =    0.30 MiB
[LLAMA][00:00:01:169] ggml_backend_metal_log_allocated_size: allocated buffer, size =  8137.66 MiB, ( 8137.72 / 49152.00)
[LLAMA][00:00:01:169] llm_load_tensors: offloading 32 repeating layers to GPU
[LLAMA][00:00:01:169] llm_load_tensors: offloading non-repeating layers to GPU
[LLAMA][00:00:01:169] llm_load_tensors: offloaded 33/33 layers to GPU
[LLAMA][00:00:01:169] llm_load_tensors:        CPU buffer size =   532.31 MiB
[LLAMA][00:00:01:169] llm_load_tensors:      Metal buffer size =  8137.64 MiB
[LLAMA][00:00:01:169] .........................................................................................
[LLAMA][00:00:01:173] llama_new_context_with_model: n_ctx      = 2048
[LLAMA][00:00:01:173] llama_new_context_with_model: n_batch    = 2048
[LLAMA][00:00:01:173] llama_new_context_with_model: n_ubatch   = 512
[LLAMA][00:00:01:173] llama_new_context_with_model: flash_attn = 0
[LLAMA][00:00:01:174] llama_new_context_with_model: freq_base  = 500000.0
[LLAMA][00:00:01:174] llama_new_context_with_model: freq_scale = 1
[LLAMA][00:00:01:174] ggml_metal_init: allocating
[LLAMA][00:00:01:174] ggml_metal_init: found device: Apple M2 Max
[LLAMA][00:00:01:174] ggml_metal_init: picking default device: Apple M2 Max
[LLAMA][00:00:01:174] ggml_metal_init: using embedded metal library
[LLAMA][00:00:01:176] ggml_metal_init: GPU name:   Apple M2 Max
[LLAMA][00:00:01:177] ggml_metal_init: GPU family: MTLGPUFamilyApple8  (1008)
[LLAMA][00:00:01:177] ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
[LLAMA][00:00:01:177] ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
[LLAMA][00:00:01:177] ggml_metal_init: simdgroup reduction support   = true
[LLAMA][00:00:01:177] ggml_metal_init: simdgroup matrix mul. support = true
[LLAMA][00:00:01:177] ggml_metal_init: hasUnifiedMemory              = true
[LLAMA][00:00:01:177] ggml_metal_init: recommendedMaxWorkingSetSize  = 51539.61 MB
[LLAMA][00:00:01:196] llama_kv_cache_init:      Metal KV buffer size =   168.00 MiB
[LLAMA][00:00:01:196] llama_new_context_with_model: KV self size  =  168.00 MiB, K (q4_1):   40.00 MiB, V (f16):  128.00 MiB
[LLAMA][00:00:01:196] llama_new_context_with_model:        CPU  output buffer size =     1.47 MiB
[LLAMA][00:00:01:197] llama_new_context_with_model:      Metal compute buffer size =   258.50 MiB
[LLAMA][00:00:01:197] llama_new_context_with_model:        CPU compute buffer size =    12.01 MiB
[LLAMA][00:00:01:197] llama_new_context_with_model: graph nodes  = 1030
[LLAMA][00:00:01:197] llama_new_context_with_model: graph splits = 2
{"cache_prompt": true,"frequency_penalty": 0,"grammar": "","image_data": [],"min_p": 0.05,"mirostat": 0,"mirostat_eta": 0.1,"mirostat_tau": 5,"n_predict": 256,"n_probs": 0,"presence_penalty": 0,"prompt": "你是一位专业、热情、聪明、机智、博学的助理警官。请尽量用严谨、严肃、简短、准确的语句说话。请不要反问。内容限制在200字内。根据接下来的上下文内容回答问题，不知道答案就说不知道，不要编造答案。上下文内容是：11月3日警方接到报案，报案人是梧桐市银杏高级中学的体育老师陈志军。据陈志军说，上午11点陈志军带领几个学生去体育仓库里拿器材，当体育仓库的门被打开后，竟发现教导主任孟惠欣倒在一片血泊当中。\n警长: 死者是谁 \n助理警官:","repeat_last_n": 256,"repeat_penalty": 1.2,"slot_id": -1,"stop": ["</s>", "助理警官:", "警长:"],"stream": true,"temperature": 0.4,"tfs_z": 1,"top_k": 40,"top_p": 0.5,"typical_p": 1}
[LLAMA][00:00:09:499] Time until first byte: 2225.8511 ms
[LLAMA][00:00:09:499] Data received:  {"content":" 教","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:09:510] Data received:  {"content":"导","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:09:551] Data received:  {"content":"主任","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:09:661] Data received:  {"content":"孟","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:09:662] Data received:  {"content":"惠","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:09:715] Data received:  {"content":"欣","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:09:769] Data received:  {"content":"。","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:09:824] Data received:  {"content":" \n","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:09:824] End of data
[LLAMA][00:00:09:824] Total prompt time: 2551.3203 ms
[LLAMA][00:00:10:517] GGML_ASSERT: /Users/runner/work/llama.cpp/llama.cpp/ggml-metal.m:2296: false
[LLAMA][00:00:10:517] GGML_ASSERT: /Users/runner/work/llama.cpp/llama.cpp/ggml-metal.m:2296: false
[LLAMA][00:00:10:517] 
[LLAMA][00:00:10:518] Exited with code 134
```

I got such exited print when I try to use LLAMA-3 model in chinese, but I don't know how to check what happened in ggml-metal.m code

**Comment by gudrob** [comment]
/Users/runner/work/llama.cpp/llama.cpp/ggml-metal.m doesn't look like a file that is part of the project.
The ggml-metal.m in the llama.cpp repo also does not have an ASSERT call in that line.

Are you using the same server file the project uses by default?

I added the metal file from the official release that I took the server file from.
Please pull the changes and tell me if that works.

**Comment by kellenwang1017** [comment]
Yes I am using the same server file pull from the project, I will try the ggml-metal.m file you've just added and keep you updated

update!

I have updated the latest changes, still I got this.

now I wonder if it has anything to do with the model I use?

I am using this one https://huggingface.co/hfl/llama-3-chinese-8b-instruct-v3-gguf, the 8 bit Q8_0 version

Should I  change the args to -cache-type-k q8_0 --cache-type-v q8_0 for LLaMAProcess.StartInfo.Arguments?

update!

I tried q8_0, still the same error!

```
  Parent node is busy setting up children, `add_child()` failed. Consider using `add_child.call_deferred(child)` instead.
  scene/main/window.cpp:1658 - Condition "!is_inside_tree()" is true.
Godot Engine v4.2.2.stable.mono.official.15073afe3 - https://godotengine.org
Vulkan API 1.2.231 - Forward+ - Using Vulkan Device #0: Apple - Apple M2 Max
 
[LLAMA][00:00:00:742] Detected MacOS on Arm64
[LLAMA][00:00:00:798] llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from ./../../llama/model/model.gguf (version GGUF V3 (latest))
[LLAMA][00:00:00:798] llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
[LLAMA][00:00:00:798] llama_model_loader: - kv   0:                       general.architecture str              = llama
[LLAMA][00:00:00:798] llama_model_loader: - kv   1:                               general.name str              = llama-3-chinese-8b-instruct-v3
[LLAMA][00:00:00:798] llama_model_loader: - kv   2:                          llama.block_count u32              = 32
[LLAMA][00:00:00:798] llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
[LLAMA][00:00:00:798] llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
[LLAMA][00:00:00:798] llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
[LLAMA][00:00:00:798] llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
[LLAMA][00:00:00:798] llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
[LLAMA][00:00:00:798] llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
[LLAMA][00:00:00:798] llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
[LLAMA][00:00:00:798] llama_model_loader: - kv  10:                          general.file_type u32              = 7
[LLAMA][00:00:00:798] llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
[LLAMA][00:00:00:798] llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
[LLAMA][00:00:00:798] llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
[LLAMA][00:00:00:798] llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
[LLAMA][00:00:00:810] llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
[LLAMA][00:00:00:813] llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
[LLAMA][00:00:00:837] llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
[LLAMA][00:00:00:837] llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
[LLAMA][00:00:00:837] llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128009
[LLAMA][00:00:00:837] llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
[LLAMA][00:00:00:837] llama_model_loader: - kv  21:               general.quantization_version u32              = 2
[LLAMA][00:00:00:837] llama_model_loader: - type  f32:   65 tensors
[LLAMA][00:00:00:837] llama_model_loader: - type q8_0:  226 tensors
[LLAMA][00:00:01:023] llm_load_vocab: special tokens cache size = 256
[LLAMA][00:00:01:044] llm_load_vocab: token to piece cache size = 0.8000 MB
[LLAMA][00:00:01:044] llm_load_print_meta: format           = GGUF V3 (latest)
[LLAMA][00:00:01:044] llm_load_print_meta: arch             = llama
[LLAMA][00:00:01:044] llm_load_print_meta: vocab type       = BPE
[LLAMA][00:00:01:044] llm_load_print_meta: n_vocab          = 128256
[LLAMA][00:00:01:044] llm_load_print_meta: n_merges         = 280147
[LLAMA][00:00:01:044] llm_load_print_meta: vocab_only       = 0
[LLAMA][00:00:01:044] llm_load_print_meta: n_ctx_train      = 8192
[LLAMA][00:00:01:044] llm_load_print_meta: n_embd           = 4096
[LLAMA][00:00:01:044] llm_load_print_meta: n_layer          = 32
[LLAMA][00:00:01:044] llm_load_print_meta: n_head           = 32
[LLAMA][00:00:01:044] llm_load_print_meta: n_head_kv        = 8
[LLAMA][00:00:01:044] llm_load_print_meta: n_rot            = 128
[LLAMA][00:00:01:044] llm_load_print_meta: n_swa            = 0
[LLAMA][00:00:01:044] llm_load_print_meta: n_embd_head_k    = 128
[LLAMA][00:00:01:044] llm_load_print_meta: n_embd_head_v    = 128
[LLAMA][00:00:01:044] llm_load_print_meta: n_gqa            = 4
[LLAMA][00:00:01:044] llm_load_print_meta: n_embd_k_gqa     = 1024
[LLAMA][00:00:01:044] llm_load_print_meta: n_embd_v_gqa     = 1024
[LLAMA][00:00:01:044] llm_load_print_meta: f_norm_eps       = 0.0e+00
[LLAMA][00:00:01:044] llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
[LLAMA][00:00:01:044] llm_load_print_meta: f_clamp_kqv      = 0.0e+00
[LLAMA][00:00:01:045] llm_load_print_meta: f_max_alibi_bias = 0.0e+00
[LLAMA][00:00:01:045] llm_load_print_meta: f_logit_scale    = 0.0e+00
[LLAMA][00:00:01:045] llm_load_print_meta: n_ff             = 14336
[LLAMA][00:00:01:045] llm_load_print_meta: n_expert         = 0
[LLAMA][00:00:01:045] llm_load_print_meta: n_expert_used    = 0
[LLAMA][00:00:01:045] llm_load_print_meta: causal attn      = 1
[LLAMA][00:00:01:045] llm_load_print_meta: pooling type     = 0
[LLAMA][00:00:01:045] llm_load_print_meta: rope type        = 0
[LLAMA][00:00:01:045] llm_load_print_meta: rope scaling     = linear
[LLAMA][00:00:01:045] llm_load_print_meta: freq_base_train  = 500000.0
[LLAMA][00:00:01:045] llm_load_print_meta: freq_scale_train = 1
[LLAMA][00:00:01:045] llm_load_print_meta: n_ctx_orig_yarn  = 8192
[LLAMA][00:00:01:045] llm_load_print_meta: rope_finetuned   = unknown
[LLAMA][00:00:01:045] llm_load_print_meta: ssm_d_conv       = 0
[LLAMA][00:00:01:045] llm_load_print_meta: ssm_d_inner      = 0
[LLAMA][00:00:01:045] llm_load_print_meta: ssm_d_state      = 0
[LLAMA][00:00:01:045] llm_load_print_meta: ssm_dt_rank      = 0
[LLAMA][00:00:01:045] llm_load_print_meta: model type       = 8B
[LLAMA][00:00:01:045] llm_load_print_meta: model ftype      = Q8_0
[LLAMA][00:00:01:045] llm_load_print_meta: model params     = 8.03 B
[LLAMA][00:00:01:045] llm_load_print_meta: model size       = 7.95 GiB (8.50 BPW) 
[LLAMA][00:00:01:045] llm_load_print_meta: general.name     = llama-3-chinese-8b-instruct-v3
[LLAMA][00:00:01:045] llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
[LLAMA][00:00:01:045] llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
[LLAMA][00:00:01:045] llm_load_print_meta: LF token         = 128 'Ä'
[LLAMA][00:00:01:045] llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
[LLAMA][00:00:01:045] llm_load_print_meta: max token length = 256
[LLAMA][00:00:01:045] llm_load_tensors: ggml ctx size =    0.27 MiB
[LLAMA][00:00:01:091] ggml_backend_metal_log_allocated_size: allocated buffer, size =  8137.66 MiB, ( 8137.72 / 49152.00)
[LLAMA][00:00:01:091] llm_load_tensors: offloading 32 repeating layers to GPU
[LLAMA][00:00:01:091] llm_load_tensors: offloading non-repeating layers to GPU
[LLAMA][00:00:01:091] llm_load_tensors: offloaded 33/33 layers to GPU
[LLAMA][00:00:01:091] llm_load_tensors:        CPU buffer size =   532.31 MiB
[LLAMA][00:00:01:091] llm_load_tensors:      Metal buffer size =  8137.64 MiB
[LLAMA][00:00:01:091] .........................................................................................
[LLAMA][00:00:01:096] llama_new_context_with_model: n_ctx      = 2048
[LLAMA][00:00:01:096] llama_new_context_with_model: n_batch    = 2048
[LLAMA][00:00:01:096] llama_new_context_with_model: n_ubatch   = 512
[LLAMA][00:00:01:096] llama_new_context_with_model: flash_attn = 1
[LLAMA][00:00:01:096] llama_new_context_with_model: freq_base  = 500000.0
[LLAMA][00:00:01:096] llama_new_context_with_model: freq_scale = 1
[LLAMA][00:00:01:096] ggml_metal_init: allocating
[LLAMA][00:00:01:096] ggml_metal_init: found device: Apple M2 Max
[LLAMA][00:00:01:096] ggml_metal_init: picking default device: Apple M2 Max
[LLAMA][00:00:01:096] ggml_metal_init: using embedded metal library
[LLAMA][00:00:01:098] ggml_metal_init: GPU name:   Apple M2 Max
[LLAMA][00:00:01:098] ggml_metal_init: GPU family: MTLGPUFamilyApple8  (1008)
[LLAMA][00:00:01:098] ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
[LLAMA][00:00:01:098] ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
[LLAMA][00:00:01:098] ggml_metal_init: simdgroup reduction support   = true
[LLAMA][00:00:01:098] ggml_metal_init: simdgroup matrix mul. support = true
[LLAMA][00:00:01:098] ggml_metal_init: hasUnifiedMemory              = true
[LLAMA][00:00:01:098] ggml_metal_init: recommendedMaxWorkingSetSize  = 51539.61 MB
[LLAMA][00:00:01:115] llama_kv_cache_init:      Metal KV buffer size =   136.00 MiB
[LLAMA][00:00:01:115] llama_new_context_with_model: KV self size  =  136.00 MiB, K (q8_0):   68.00 MiB, V (q8_0):   68.00 MiB
[LLAMA][00:00:01:115] llama_new_context_with_model:        CPU  output buffer size =     1.47 MiB
[LLAMA][00:00:01:115] llama_new_context_with_model:      Metal compute buffer size =   266.50 MiB
[LLAMA][00:00:01:115] llama_new_context_with_model:        CPU compute buffer size =    12.01 MiB
[LLAMA][00:00:01:115] llama_new_context_with_model: graph nodes  = 903
[LLAMA][00:00:01:115] llama_new_context_with_model: graph splits = 66
[LLAMA][00:00:03:027] {"cache_prompt": true,"frequency_penalty": 0,"grammar": "","image_data": [],"min_p": 0.05,"mirostat": 0,"mirostat_eta": 0.1,"mirostat_tau": 5,"n_predict": 256,"n_probs": 0,"presence_penalty": 0,"prompt": "\u003c|start_header_id|\u003esystem\u003c|end_header_id|\u003e\nYou are 助理警官, a professional, smart, supportive assitant who speaks only Chinese. You will answer each quesion asked by user 警长 using precise and serious expressions with less than 200 words. Don\u0027t ask 警长 any question. Your answer must be based on the context provided in Chinese. Don\u0027t make up anything. If you don\u0027t know the answer just say that this question has nothing to do with this case. The context in Chinese is：11月3日警方接到报案，报案人是梧桐市银杏高级中学的体育老师陈志军。据陈志军说，上午11点陈志军带领几个学生去体育仓库里拿器材，当体育仓库的门被打开后，竟发现教导主任孟惠欣倒在一片血泊当中。陈志军立刻让学生通知了校长，同时用自己的手机报了警。\u003c|eot_id|\u003e\n\u003c|start_header_id|\u003euser\u003c|end_header_id|\u003e:你好\n\u003c|eot_id|\u003e\u003c|start_header_id|\u003eassistant\u003c|end_header_id|\u003e:","repeat_last_n": 256,"repeat_penalty": 1.2,"slot_id": -1,"stop": ["<|eot_id|>"],"stream": true,"temperature": 0.01,"tfs_z": 1,"top_k": 45,"top_p": 0.01,"min_p": 0.01,"seed": 0}
[LLAMA][00:00:15:835] Time until first byte: 12807.3981 ms
[LLAMA][00:00:15:835] Data received: {"content":"您","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:15:901] Data received: {"content":"好","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:15:975] Data received: {"content":"，","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:16:042] Data received: {"content":"警","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:16:117] Data received: {"content":"长","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:16:192] Data received: {"content":"！","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:16:259] Data received: {"content":"我","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:16:334] Data received: {"content":"是","stop":false,"id_slot":0,"multimodal":false}
[LLAMA][00:00:16:398] /Users/runner/work/llama.cpp/llama.cpp/ggml/src/ggml-metal.m:2324: fatal error
[LLAMA][00:00:16:398] /Users/runner/work/llama.cpp/llama.cpp/ggml/src/ggml-metal.m:2324: fatal error
[LLAMA][00:00:16:399] 
[LLAMA][00:00:16:399] Exited with code 134
[LLAMA][00:00:16:400] Data received: {"content":"助","stop":false,"id_slot":0,"multimodal":false}
```

update!

I changed contextSize to 8192, now log content changed to this:
```
[LLAMA][00:00:18:619] Exception while parsing AI response: System.Text.Json.JsonException: Expected end of string, but instead reached end of data. Path: $.prompt | LineNumber: 0 | BytePositionInLine: 4084.
 ---> System.Text.Json.JsonReaderException: Expected end of string, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 4084.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at AIRPG.LLaMA.Generate(Session session, String text, Int32 predictTokens, Single repeatPenalty, Single temperature) in /Users/kellenwang/KW_CLOUD/GDPROJECT/godot-ai-rpg/scripts/LLaMA.cs:line 111
[LLAMA][00:00:18:619] Exception while parsing AI response: System.Text.Json.JsonException: '0xE6' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0xE6' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at AIRPG.LLaMA.Generate(Session session, String text, Int32 predictTokens, Single repeatPenalty, Single temperature) in /Users/kellenwang/KW_CLOUD/GDPROJECT/godot-ai-rpg/scripts/LLaMA.cs:line 111
[LLAMA][00:00:18:619] Total prompt time: 14007.9523 ms
```

Though it still gives this error at the beginning, it seems to work now at least
